Meituan/urls.py
from django.urls import path

from . import views
app_name = 'Meituan'
urlpatterns = [
	path("", views.home_page, name='home_page')
	]

cafe/urls.py
from django.urls import include, path 
from django.contrib import admin

urlpatterns = [ 
     path('', include('Meituan.urls')), 
     path('admin/', admin.site.urls),
]

Meituan/models.py
from django.db import models

# Create your models here.

Meituan/views.py
from django.shortcuts import render

def home_page(request):

    if request.method == 'POST':
       item = request.POST.get('item')
       address = request.POST.get("address")

       return render(request, 'Meituan/home_page.html', {'item': item, 'address': address})

    return render(request, 'Meituan/home_page.html')

Meituan/templates/Meituan/home_page.html
<!DOCTYPE html>
<html>
<head>
 <title>Kool Karen Meituan</title>
</head>
<body>
 <!-- Site Header -->
 <h1>Kool Karen Meituan</h1>
  <p>Your convenience is our duty</p>

<!-- Blog Post -->
 <h2>Here are all our items!</h2>

 <!--Item 1-->

 <p>Water: 12RMB</p>
 <img src="https://content.etilize.com/Out-of-Package/1027090117.jpg">

 <br>
 <!--item 2-->
 <p>Cherry Cake: 28RMB</p>
 <img src="https://www.sweetandsavorybyshinee.com/wp-content/uploads/2017/08/3-Ingredient-Chocolate-Cherry-Sheet-Cake-2.jpg">
 <!--item 3 -->
 <p>Hot dog: 35RMB</p>
<img src="http://mobile-cuisine.com/wp-content/uploads/2012/09/hot-dog-fun-facts.jpg">

<!--Order Form-->
<h2>Place your Order</h2>
<form action="{% url 'Meituan:home_page' %}" method="POST">
 {% csrf_token %}
 <input type="order" placeholder="Please Type Which Item You Want" name="order"><br><br>
 <textarea name="address" placeholder="Please Type Your Address"></textarea><br>
 <input type="submit" value="Place Your Order!">
 </form>

<!--Show Order-->
<h1>Your order</h1>
<p>Item Ordered:{{item}}</p>
<p>Delivery Address:{{address}}</p>

</body>
</html>